/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Logic;

import Data.Restaurante;

/**
 *
 * @author mrdan
 */
public class MenuParaIngresarDatos extends javax.swing.JFrame {

    private int tipoDato = 0;
    private String nombre;
    private String direccion;
    public Bestellen2 app;
    private String descripcion;
    private int precio;
    private String email;
    private String contraseña;
    private Integer cedula;
    private Integer telefono;

    public void setTipoDato(int tipoDato) {
        this.tipoDato = tipoDato;
    }
    
    String txtIngresarRestaurante = "Ingrese el nombre del restaurante";
    String txtIngresarRestaurante2 = "Ingrese la dirección del restaurante";
    String txtIngresarPlato = "Ingrese el nombre del plato";
    String txtIngresarPlato2 = "Ingrese la descripción del plato";
    String txtIngresarPlato3 = "Ingrese el precio del plato";
    String txtIngresarBebida = "Ingrese el nombre de la bebida";
    String txtIngresarBebida2 = "Ingrese la descripción de la bebida";
    String txtIngresarBebida3 = "Ingrese el precio de la bebida";
    String txtIngresarBebida4 =  "¿Contiene alcohol?";
    String txtIngresarCliente = "Ingrese el nombre del cliente";
    String txtIngresarCliente2 = "Ingrese el email del cliente";
    String txtIngresarCliente3 = "Ingrese la contraseña del cliente";
    String txtIngresarCliente4 = "Ingrese la cedula del cliente";
    String txtIngresarCliente5 = "Ingrese el telefono del cliente";

    

    
    public MenuParaIngresarDatos(Bestellen2 apli) {
        app = apli;
        initComponents();
    }
    public MenuParaIngresarDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese el nombre del restaurante");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(328, 328, 328))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jButton1)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        switch (tipoDato) {
                    case 1:
                        nombre = jTextField1.getText();
                        setTipoDato(2);
                        break;
                    case 2:
                        direccion = jTextField1.getText();
                        app.crearRestaurante(nombre, direccion);
                        
                        MenuDelRestaurante menu = new MenuDelRestaurante(app);
                        menu.setVisible(true);
                        this.setVisible(false);
                        break;
                    case 3:
                        nombre = jTextField1.getText();
                        setTipoDato(4);
                        break;
                    case 4:
                        descripcion = jTextField1.getText();
                        setTipoDato(5);
                        break;
                    case 5:
                        //validar que sea un entero
                        precio = Integer.valueOf(jTextField1.getText());
                        app.crearPlato(app.restauranteSeleccionado,nombre, descripcion,precio);
                        
                        menu = new MenuDelRestaurante(app);
                        menu.setVisible(true);
                        this.setVisible(false);
                        break;
                    case 6:
                        nombre = jTextField1.getText();
                        setTipoDato(7);
                        break;
                    case 7:
                        descripcion = jTextField1.getText();
                        setTipoDato(8);
                        break;
                    case 8:
                        precio = Integer.valueOf(jTextField1.getText());
                        setTipoDato(9);
                        break;
                    case 9:
                        if(jTextField1.getText().contains("si")){
                            app.crearBebida(app.restauranteSeleccionado,nombre, descripcion,precio, true);
                        }else 
                            app.crearBebida(app.restauranteSeleccionado, nombre, descripcion,precio, false);
                        
                        menu = new MenuDelRestaurante(app);
                        menu.setVisible(true);
                        this.setVisible(false);
                        break;
                    case 10:
                        nombre = jTextField1.getText();
                        setTipoDato(11);
                        break;
                    case 11:
                        email = jTextField1.getText();
                        setTipoDato(12);
                        break;
                    case 12:
                        contraseña = jTextField1.getText();
                        setTipoDato(13);
                        break;
                    case 13:
                        cedula = Integer.valueOf(jTextField1.getText());
                        setTipoDato(14);
                        break;
                    case 14:
                        telefono = Integer.valueOf(jTextField1.getText());
                        app.crearUsuario(nombre, email, cedula, telefono, contraseña);
                        
                        Administrar dd = new Administrar(app,1);
                        dd.setVisible(true);
                        this.setVisible(false);
                        break;
                    default:
                        jLabel1.setText("No hay datos");
                }
        ingresarDatos();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MenuParaIngresarDatos().setVisible(true);
            }
        });
    }
    
    public void ingresarDatos(){
        switch (tipoDato) {
                    case 1:
                        jLabel1.setText(txtIngresarRestaurante);
                        break;
                    case 2:
                        jLabel1.setText(txtIngresarRestaurante2);
                        System.out.println("entro");
                        break;
                    case 3:
                        jLabel1.setText(txtIngresarPlato);
                        break;
                    case 4:
                        jLabel1.setText(txtIngresarPlato2);
                        break;
                    case 5:
                        jLabel1.setText(txtIngresarPlato3);
                        break;
                    case 6:
                        jLabel1.setText(txtIngresarBebida);
                        break;
                    case 7:
                        jLabel1.setText(txtIngresarBebida2);
                        break;
                    case 8:
                        jLabel1.setText(txtIngresarBebida3);
                        break;
                    case 9:
                        jLabel1.setText(txtIngresarBebida4);
                        break;
                    case 10:
                        jLabel1.setText(txtIngresarCliente);
                        break;
                    case 11:
                        jLabel1.setText(txtIngresarCliente2);
                        break;
                    case 12:
                        jLabel1.setText(txtIngresarCliente3);
                        break;
                    case 13:
                        jLabel1.setText(txtIngresarCliente4);
                        break;
                    case 14:
                        jLabel1.setText(txtIngresarCliente5);
                        break;
                    default:
                        jLabel1.setText("No hay datos");
                }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
